AWSTemplateFormatVersion: 2010-09-09
Description: URL rewrite for React Router SPA with client-side routing

Parameters:
  AutoPublishParam:
    Description: Whether to automatically publish on creation
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  RewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: !Ref AutoPublishParam
      FunctionCode: !Sub |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;
          var paths = ['assets/', 'img/', '.xml', '.webmanifest', '.js', 'robots.txt']
          var isServerPath = (path) => uri.includes(path);

          if (!paths.some(isServerPath)) {
            request.uri = '/';
          }

          return request;
        }
      FunctionConfig:
        Comment: "Rewrite the URL for SPAs with client-side routing"
        Runtime: cloudfront-js-1.0
      Name: !Sub "${AWS::StackName}-rewriteFunction"

Outputs:
  FunctionArn:
    Description: CloudFront Function
    Value: !GetAtt RewriteFunction.FunctionMetadata.FunctionARN
